const $ = s => document.querySelector(s);
const stage = $('#stage'), ctx = stage.getContext('2d');
let media=[], cues=[], selectedStyle='off', current=0, playing=false, raf, installPrompt;
const audio=$('#audio');
let audioCtx, audioSource, audioDestination;
let ffmpeg=null, ffmpegLoaded=false;
function initAudioContext(){
  if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();audioSource=audioCtx.createMediaElementSource(audio);audioDestination=audioCtx.createMediaStreamDestination();audioSource.connect(audioDestination);audioSource.connect(audioCtx.destination);}
}
function timecode(s){const [h,m,rest]=s.replace(',','.').split(':');const [sec,ms='0']=rest.split('.');return +h*3600+ +m*60+ +sec+ +(ms+'00').slice(0,3)/1000;}
function fmt(t){t=Math.max(0,t);return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function parseSrt(text){return text.trim().split(/\n\s*\n/).map(block=>{const l=block.split(/\r?\n/),i=l.findIndex(x=>x.includes('-->'));if(i<0)return null;return{start:timecode(l[i].split('-->')[0].trim()),end:timecode(l[i].split('-->')[1].trim()),text:l.slice(i+1).join(' ').replace(/<[^>]+>/g,'').trim()};}).filter(Boolean);}
function sortFiles(a,b){return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'});}
function activeCue(t){return cues.findIndex(c=>t>=c.start&&t<c.end);}
function sceneAt(t){const i=activeCue(t);return i<0?Math.max(0,Math.min(media.length-1,Math.floor(t/5))):i%Math.max(1,media.length);}
function setCanvasSize(){const res=$('#resolution').value;if(res==='1440'){stage.width=2560;stage.height=1440;}else{stage.width=1920;stage.height=1080;}}
function drawFrame(idx,t,alpha=1){const item=media[idx];if(!item)return;const p=cues[activeCue(t)];const progress=p?Math.min(1,Math.max(0,(t-p.start)/(p.end-p.start))):0;let scale=1,x=0,y=0;const motion=$('#motion').value;if(motion==='zoomIn'||(motion==='sequence'&&idx%2===0))scale=1+progress*.08;else if(motion==='zoomOut'||motion==='sequence')scale=1.08-progress*.08;if(motion==='panLeft')x=-progress*35;if(motion==='panRight')x=progress*35;const obj=item.el;if(obj.tagName==='VIDEO'){const target=Math.max(0,t-(p?.start||0));if(Math.abs(obj.currentTime-target)>.25)obj.currentTime=target;}const iw=obj.videoWidth||obj.naturalWidth||stage.width,ih=obj.videoHeight||obj.naturalHeight||stage.height;const fit=$('#fit').value,r=fit==='contain'?Math.min(stage.width/iw,stage.height/ih):Math.max(stage.width/iw,stage.height/ih);const w=iw*r*scale,h=ih*r*scale;ctx.save();ctx.globalAlpha=alpha;ctx.translate(stage.width/2+x,stage.height/2+y);ctx.drawImage(obj,-w/2,-h/2,w,h);ctx.restore();}
function draw(t=0){setCanvasSize();ctx.clearRect(0,0,stage.width,stage.height);ctx.fillStyle='#060914';ctx.fillRect(0,0,stage.width,stage.height);if(!media.length)return;const idx=sceneAt(t),p=cues[activeCue(t)],transition=$('#transition').value;if(transition==='fade'&&p&&(t-p.start)<.5&&idx>0){const fp=(t-p.start)/.5;drawFrame(idx-1,t,1-fp);drawFrame(idx,t,fp);}else drawFrame(idx,t,1);const effect=$('#effect').value;if(effect==='warm'){ctx.fillStyle='rgba(255,150,40,.12)';ctx.fillRect(0,0,stage.width,stage.height);}if(effect==='cinema'){ctx.fillStyle='rgba(10,14,26,.18)';ctx.fillRect(0,0,stage.width,stage.height);}if(effect==='vignette'){const g=ctx.createRadialGradient(stage.width/2,stage.height/2,120,stage.width/2,stage.height/2,stage.width/2);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(0,0,0,.72)');ctx.fillStyle=g;ctx.fillRect(0,0,stage.width,stage.height);}if(p&&selectedStyle!=='off')drawSubtitle(p.text);$('#timeline').value=t;$('#timeLabel').textContent=`${fmt(t)} / ${fmt(audio.duration||cues.at(-1)?.end||0)}`;document.querySelectorAll('.scene').forEach((e,i)=>e.classList.toggle('active',i===idx));}
function drawSubtitle(text){const pos=$('#subPosition').value,size=$('#subSize').value,scaleFactor=stage.width/960,baseFs=size==='large'?34:size==='medium'?27:21,fs=baseFs*scaleFactor;let y=stage.height-(55*scaleFactor);if(pos==='center')y=stage.height/2;if(pos==='top')y=60*scaleFactor;ctx.font=`800 ${fs}px Arial`;ctx.textAlign='center';const max=stage.width-(110*scaleFactor),words=text.split(' ');let lines=[],line='';for(const w of words){if(ctx.measureText(line+' '+w).width>max){lines.push(line);line=w;}else line+=(line?' ':'')+w;}if(line)lines.push(line);const lh=fs*1.3,style=selectedStyle;if(['box','neon','lower'].includes(style)){ctx.fillStyle=style==='neon'?'rgba(100,20,190,.78)':'rgba(0,0,0,.78)';ctx.fillRect(55*scaleFactor,y-fs,stage.width-(110*scaleFactor),lines.length*lh+fs*.5);}ctx.fillStyle=style==='yellow'||style==='karaoke'?'#ffe35e':'#fff';ctx.strokeStyle='rgba(0,0,0,.8)';ctx.lineWidth=5*scaleFactor;lines.forEach((l,i)=>{const yy=y+i*lh;ctx.strokeText(l,stage.width/2,yy);ctx.fillText(l,stage.width/2,yy);});}
function loadMedia(files){media.forEach(m=>{try{URL.revokeObjectURL(m.url)}catch{}});media=[];[...files].sort(sortFiles).forEach(file=>{const el=file.type.startsWith('video/')?document.createElement('video'):new Image();const url=URL.createObjectURL(file);el.src=url;el.muted=true;el.playsInline=true;el.crossOrigin='anonymous';if(el.tagName==='VIDEO'){el.preload='auto';el.load();}media.push({name:file.name,el,url});});$('#emptyState').style.display='none';$('#status').textContent=`${media.length} medya hazır`;draw(current);}
$('#mediaInput').onchange=e=>loadMedia(e.target.files);
$('#audioInput').onchange=e=>{const f=e.target.files[0];if(f){audio.src=URL.createObjectURL(f);$('#audioLabel').textContent=f.name;initAudioContext();}};
$('#srtInput').onchange=async e=>{const f=e.target.files[0];if(f){cues=parseSrt(await f.text());$('#srtLabel').textContent=f.name;$('#timeline').max=cues.at(-1)?.end||1;renderScenes();$('#status').textContent=`${cues.length} altyazı bloğu hazır`;draw(current);}};
function renderScenes(){const box=$('#scenes');box.innerHTML='';$('#sceneCount').textContent=`${cues.length} sahne`;cues.forEach((c,i)=>{const d=document.createElement('div');d.className='scene';d.innerHTML=`<strong>SAHNE ${String(i+1).padStart(2,'0')}</strong><time>${fmt(c.start)} — ${fmt(c.end)}</time><p>${c.text}</p>`;d.onclick=()=>{current=c.start;audio.currentTime=current;draw(current)};box.append(d);});}
$('#playBtn').onclick=()=>{initAudioContext();if(audioCtx?.state==='suspended')audioCtx.resume();playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶';if(playing){audio.play().catch(()=>{});tick();}else{audio.pause();cancelAnimationFrame(raf);}};
audio.ontimeupdate=()=>{current=audio.currentTime;draw(current)};audio.onloadedmetadata=()=>{$('#timeline').max=audio.duration;draw(current)};$('#timeline').oninput=e=>{current=+e.target.value;audio.currentTime=current;draw(current)};
function tick(){if(!playing)return;draw(audio.currentTime);raf=requestAnimationFrame(tick);}
document.querySelectorAll('.style').forEach(b=>b.onclick=()=>{document.querySelectorAll('.style').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedStyle=b.dataset.style;draw(current)});[...document.querySelectorAll('select')].forEach(s=>s.onchange=()=>draw(current));
async function ensureFFmpeg(){if(ffmpegLoaded)return; if(!window.FFmpeg)throw new Error('MP4 motoru yüklenemedi. İnternet bağlantısını kontrol et.');ffmpeg=FFmpeg.createFFmpeg({log:false,corePath:'https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js'});$('#status').textContent='MP4 motoru hazırlanıyor…';await ffmpeg.load();ffmpegLoaded=true;}
async function renderWebM(){initAudioContext();if(audioCtx?.state==='suspended')await audioCtx.resume();const fps=Number($('#quality').value),stream=stage.captureStream(fps),tracks=[...stream.getVideoTracks()];if(audioDestination)tracks.push(...audioDestination.stream.getAudioTracks());const combined=new MediaStream(tracks);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm';const rec=new MediaRecorder(combined,{mimeType:mime});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);await new Promise((resolve,reject)=>{rec.onstop=resolve;rec.onerror=reject;rec.start();audio.currentTime=0;audio.play().catch(()=>{});const end=audio.duration||cues.at(-1)?.end||Math.max(5,media.length*5);let t=0;const step=()=>{draw(t);const pct=Math.min(100,(t/end)*100);$('#progressBar').style.width=pct+'%';t+=1/fps;if(t<end)setTimeout(step,1000/fps);else{audio.pause();rec.stop();}};step();});return new Blob(chunks,{type:'video/webm'});}
async function convertWebMtoMP4(webmBlob){await ensureFFmpeg();const data=new Uint8Array(await webmBlob.arrayBuffer());ffmpeg.FS('writeFile','input.webm',data);await ffmpeg.run('-i','input.webm','-c:v','libx264','-preset','veryfast','-pix_fmt','yuv420p','-movflags','+faststart','-c:a','aac','-b:a','192k','output.mp4');const out=ffmpeg.FS('readFile','output.mp4');try{ffmpeg.FS('unlink','input.webm');ffmpeg.FS('unlink','output.mp4');}catch{}return new Blob([out.buffer],{type:'video/mp4'});}
$('#renderBtn').onclick=async()=>{if(!media.length){alert('Önce medya yükleyin.');return;}if(!audio.src){alert('MP4 için seslendirme dosyası yükleyin.');return;}$('#renderBtn').disabled=true;$('#download').hidden=true;$('#renderProgress').hidden=false;$('#progressBar').style.width='0%';try{const format=$('#format').value;let blob=await renderWebM();if(format==='mp4'){ $('#status').textContent='WebM tamamlandı, MP4 dönüştürülüyor…';blob=await convertWebMtoMP4(blob);}const ext=format==='mp4'?'mp4':'webm';const url=URL.createObjectURL(blob);const a=$('#download');a.href=url;a.download=`kurgu-canavari.${ext}`;a.textContent=`İndir: kurgu-canavari.${ext}`;a.hidden=false;$('#progressBar').style.width='100%';$('#status').textContent=`${ext.toUpperCase()} hazır`;}catch(err){console.error(err);alert('Dışa aktarma sırasında hata oluştu: '+(err?.message||err));$('#status').textContent='Dışa aktarma başarısız';}finally{$('#renderBtn').disabled=false;setTimeout(()=>$('#renderProgress').hidden=true,1200);}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();installPrompt=null}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');draw();
